// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageLocksStore is an autogenerated mock type for the MessageLocksStore type
type MessageLocksStore struct {
	mock.Mock
}

// Obtain provides a mock function with given fields: mID, mType
func (_m *MessageLocksStore) Obtain(mID string, mType string) bool {
	ret := _m.Called(mID, mType)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(mID, mType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
