// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

import time "time"
import types "bitbucket.org/mrpoundsign/poundbot/types"

// RaidAlertsStore is an autogenerated mock type for the RaidAlertsStore type
type RaidAlertsStore struct {
	mock.Mock
}

// AddInfo provides a mock function with given fields: alertIn, ed
func (_m *RaidAlertsStore) AddInfo(alertIn time.Duration, ed types.EntityDeath) error {
	ret := _m.Called(alertIn, ed)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration, types.EntityDeath) error); ok {
		r0 = rf(alertIn, ed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReady provides a mock function with given fields: _a0
func (_m *RaidAlertsStore) GetReady(_a0 *[]types.RaidNotification) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]types.RaidNotification) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: _a0
func (_m *RaidAlertsStore) Remove(_a0 types.RaidNotification) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RaidNotification) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
