// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserInfoGetter is an autogenerated mock type for the UserInfoGetter type
type UserInfoGetter struct {
	mock.Mock
}

// GetDiscordID provides a mock function with given fields:
func (_m *UserInfoGetter) GetDiscordID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPlayerID provides a mock function with given fields:
func (_m *UserInfoGetter) GetPlayerID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
