// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import types "mrpoundsign.com/poundbot/types"

// ChatsAccessLayer is an autogenerated mock type for the ChatsAccessLayer type
type ChatsAccessLayer struct {
	mock.Mock
}

// Log provides a mock function with given fields: _a0
func (_m *ChatsAccessLayer) Log(_a0 types.ChatMessage) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.ChatMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
