// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import types "mrpoundsign.com/poundbot/types"

// ClansStore is an autogenerated mock type for the ClansStore type
type ClansStore struct {
	mock.Mock
}

// Remove provides a mock function with given fields: tag
func (_m *ClansStore) Remove(tag string) error {
	ret := _m.Called(tag)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveNotIn provides a mock function with given fields: tags
func (_m *ClansStore) RemoveNotIn(tags []string) error {
	ret := _m.Called(tags)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: _a0
func (_m *ClansStore) Upsert(_a0 types.Clan) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Clan) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
